global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "/etc/prometheus/rules/*.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "backend-services"
    static_configs:
      - targets: ["backend-1:3001", "backend-2:3001", "backend-3:3001"]
    metrics_path: "/api/metrics"
    scrape_interval: 10s

  # Remove the nginx job since it doesn't have metrics endpoint
  # - job_name: "nginx"
  #   static_configs:
  #     - targets: ["nginx:80"]
  #   metrics_path: "/metrics"
  #   scrape_interval: 30s

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "postgres"
    static_configs:
      - targets: ["postgres-master:5432"]

  - job_name: "redis"
    static_configs:
      - targets: ["redis-master:6379"]
