apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-master-config
data:
  postgresql.conf: |
    listen_addresses = '*'
    max_connections = 100
    shared_buffers = 128MB
    wal_level = replica
    max_wal_senders = 3
    wal_keep_segments = 32
    hot_standby = on
