apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-exporter-config
  namespace: fragrance-palette
data:
  postgres_exporter.yml: |
    auth_modules:
      default:
        type: userpass
        userpass:
          username: postgres
          password: ${POSTGRES_PASSWORD}
        options:
          sslmode: disable
    datasource: postgresql://postgres:${POSTGRES_PASSWORD}@localhost:5432/fragrances?sslmode=disable
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-exporter
  namespace: fragrance-palette
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-exporter
  template:
    metadata:
      labels:
        app: postgres-exporter
    spec:
      containers:
        - name: postgres-exporter
          image: prometheuscommunity/postgres-exporter:latest
          env:
            - name: DATA_SOURCE_NAME
              value: "postgresql://postgres:$(POSTGRES_PASSWORD)@postgres-master:5432/fragrances?sslmode=disable"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
          ports:
            - containerPort: 9187
