apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-replica
  namespace: fragrance-palette
spec:
  serviceName: postgres-replica
  replicas: 2
  selector:
    matchLabels:
      app: postgres-replica
  template:
    metadata:
      labels:
        app: postgres-replica
    spec:
      containers:
        - name: postgres
          image: postgres:15
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
            - name: POSTGRES_REPLICATION_USER
              value: replicator
            - name: POSTGRES_REPLICATION_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: replication-password
            - name: POSTGRES_MASTER_SERVICE
              value: postgres-master.fragrance-palette.svc.cluster.local
          command:
            - /bin/bash
            - -c
            - |
              # Wait for master to be ready
              until pg_isready -h $POSTGRES_MASTER_SERVICE -p 5432 -U postgres; do
                echo "Waiting for master..."
                sleep 2
              done

              # Create base backup from master
              if [ ! -f /var/lib/postgresql/data/postgresql.conf ]; then
                pg_basebackup -h $POSTGRES_MASTER_SERVICE -D /var/lib/postgresql/data -U replicator -v -P -W
                
                # Configure replica
                echo "standby_mode = 'on'" >> /var/lib/postgresql/data/postgresql.conf
                echo "primary_conninfo = 'host=$POSTGRES_MASTER_SERVICE port=5432 user=replicator'" >> /var/lib/postgresql/data/postgresql.conf
                echo "primary_slot_name = 'replica_slot'" >> /var/lib/postgresql/data/postgresql.conf
                echo "hot_standby = on" >> /var/lib/postgresql/data/postgresql.conf
                echo "max_connections = 100" >> /var/lib/postgresql/data/postgresql.conf
                
                touch /var/lib/postgresql/data/standby.signal
              fi

              postgres
          ports:
            - containerPort: 5432
          resources:
            requests:
              memory: "256Mi"
              cpu: "125m"
            limits:
              memory: "512Mi"
              cpu: "250m"
          volumeMounts:
            - name: postgres-replica-storage
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pg_isready -U postgres
            initialDelaySeconds: 30
            periodSeconds: 10
  volumeClaimTemplates:
    - metadata:
        name: postgres-replica-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "fast-ssd"
        resources:
          requests:
            storage: 50Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-replica
  namespace: fragrance-palette
spec:
  selector:
    app: postgres-replica
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
