apiVersion: v1
kind: Secret
metadata:
  name: database-secret
type: Opaque
data:
  postgres-password: cG9zdGdyZXNtYXN0ZXI= # postgresmaster (base64)
  replication-password: cmVwbGljYXRvcjEyMw== # replicator123 (base64)
  master-url: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBvc3RncmVzbWFzdGVyQHBvc3RncmVzLW1hc3Rlci1zZXJ2aWNlOjU0MzIvZnJhZ3JhbmNlcw==
  replica-url: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBvc3RncmVzbWFzdGVyQHBvc3RncmVzLXJlcGxpY2Etc2VydmljZTo1NDMyL2ZyYWdyYW5jZXM=
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  jwt-secret: eW91ci1qd3Qtc2VjcmV0LWtleQ== # your-jwt-secret-key (base64)
  hf-token: eW91ci1odWdnaW5nZmFjZS10b2tlbg== # your-huggingface-token (base64)
